### ISSUE TITLE
What is the difference from http-problem-details

### ISSUE THREAD

**Issue by ackvf** [PDMLab/http-problem#25]
What is the actual difference with https://github.com/PDMLab/http-problem-details and should I use it instead?

**Comment by AlexZeitler** [comment]
`http-problem` was the first approach to implement RFC7807. It is still there because it is used in several projects. `http-problem-details` is a more recent implementation written in TypeScript with extensibility in mind. Most efforts will be put in this one but if somebody sends a PR for the old implementation it is likely it’ll be merged as well.
So if you’re not using an RFC7807 library right now, I would recommend `http-problem-details` and its downstream libraries.

**Comment by ackvf** [comment]
Thank you Alex, would you consider adding this note to the description as well?

**Comment by AlexZeitler** [comment]
@ackvf Done, see #26
